package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/jluntpcty/contextual/internal/config"
	"github.com/jluntpcty/contextual/internal/logger"
	"github.com/jluntpcty/contextual/internal/planner"
	"github.com/jluntpcty/contextual/internal/prompt"
	"github.com/jluntpcty/contextual/internal/spider"
	"github.com/jluntpcty/contextual/internal/types"
	"github.com/jluntpcty/contextual/pkg/version"
)

func main() {
	// Route stdlib log output to stderr; used only for fatal pre-logger errors.
	log.SetOutput(os.Stderr)
	log.SetFlags(0)

	args := os.Args[1:]

	// Detect 'version' subcommand.
	if len(args) > 0 && args[0] == "version" {
		fmt.Println(version.Version)
		os.Exit(0)
	}

	// Detect 'plan' subcommand.
	planMode := false
	if len(args) > 0 && args[0] == "plan" {
		planMode = true
		args = args[1:]
	}

	// Parse flags.
	fs := flag.NewFlagSet("contextual", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	verbose := fs.Bool("verbose", false, "Print fetch details to stderr")
	fs.BoolVar(verbose, "v", false, "Print fetch details to stderr (shorthand)")
	progress := fs.Bool("progress", false, "Print a progress indicator to stderr")
	fs.BoolVar(progress, "p", false, "Print a progress indicator to stderr (shorthand)")

	if err := fs.Parse(args); err != nil {
		os.Exit(1)
	}
	itemArgs := fs.Args()

	if len(itemArgs) == 0 {
		if planMode {
			fmt.Fprintln(os.Stderr, "Usage: contextual plan [--verbose|-v] [--progress|-p] <item> [<item> ...]")
		} else {
			fmt.Fprintln(os.Stderr, "Usage: contextual [--verbose|-v] [--progress|-p] <item> [<item> ...]")
		}
		os.Exit(1)
	}

	// Determine logger mode.
	logMode := logger.ModeSilent
	switch {
	case *verbose:
		logMode = logger.ModeVerbose
	case *progress:
		logMode = logger.ModeProgress
	}

	lg, err := logger.New(logMode)
	if err != nil {
		log.Printf("[ERROR] Could not initialise logger: %v", err)
		os.Exit(1)
	}
	defer lg.Close()

	cfg, err := config.Load()
	if err != nil {
		lg.Warn("Could not load config: %v — see contextual.config.example.yml for setup instructions", err)
		cfg = &config.Config{}
	}

	s := spider.New(cfg, lg)
	items, err := s.Run(itemArgs)
	if err != nil {
		lg.Error("%v", err)
		os.Exit(1)
	}

	// Resolve the output directory.
	// In plan mode: agent_docs/plans/<slug>/ or ./<slug>/
	// In fetch mode: current working directory
	var outputDir string
	if planMode {
		if len(items) == 0 {
			lg.Error("No items fetched; cannot produce a plan file.")
			os.Exit(1)
		}
		outputDir, err = planner.ResolveOutputDir(items[0])
		if err != nil {
			lg.Error("Could not determine output directory: %v", err)
			os.Exit(1)
		}
	} else {
		outputDir, err = os.Getwd()
		if err != nil {
			lg.Error("Could not determine working directory: %v", err)
			os.Exit(1)
		}
	}

	// Write context.md — confirm overwrite if it already exists.
	contextPath := filepath.Join(outputDir, "context.md")
	if !planner.ConfirmOverwrite(contextPath) {
		fmt.Fprintln(os.Stderr, "Aborted.")
		os.Exit(1)
	}

	f, err := os.Create(contextPath)
	if err != nil {
		lg.Error("Could not create context file: %v", err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprintln(f, "This file was generated by the `contextual` tool. It contains fetched content")
	fmt.Fprintln(f, "from one or more sources (Jira issues, Confluence pages, and/or web pages),")
	fmt.Fprintln(f, "assembled to provide context for an AI agent or developer.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "Each section below represents a single fetched item. Sections are separated by")
	fmt.Fprintln(f, "a line of '=' characters and begin with a short metadata header (TYPE, ID, URL,")
	fmt.Fprintln(f, "TITLE), followed by the item's full content in Markdown format.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "The FIRST item is the primary subject — it corresponds directly to the first")
	fmt.Fprintln(f, "argument passed on the command line. All subsequent items are supporting context")
	fmt.Fprintln(f, "discovered via links, references, or related content within the primary item.")
	fmt.Fprintln(f, "")
	fmt.Fprintf(f, "Total items: %d\n", len(items))
	fmt.Fprintln(f)

	var bytesWritten int
	for i, item := range items {
		// Calculate size of item: content + approximate metadata overhead
		itemSize := len(item.Content) + 300
		if cfg.MaxContextLength > 0 && bytesWritten+itemSize > cfg.MaxContextLength {
			lg.Info("Reached max context length (%d bytes); truncating remaining %d items", cfg.MaxContextLength, len(items)-i)
			break
		}
		writeItem(f, item)
		bytesWritten += itemSize
	}

	if !planMode {
		fmt.Println(contextPath)
		return
	}

	// Plan mode: build prompt and invoke planner to write plan.md.
	primaryItem := items[0]
	promptText := prompt.BuildPlanPrompt(contextPath, primaryItem)

	lg.Info("Context file: %s", contextPath)
	lg.Info("Plan file will be written to: %s", filepath.Join(outputDir, "plan.md"))

	if err := planner.RunPlanner(cfg.Planner, promptText, outputDir, lg); err != nil {
		lg.Error("%v", err)
		os.Exit(1)
	}

	fmt.Println(filepath.Join(outputDir, "plan.md"))
}

func writeItem(f *os.File, item types.Item) {
	sep := strings.Repeat("=", 80)
	fmt.Fprintln(f, sep)
	fmt.Fprintf(f, "TYPE: %s\n", itemTypeName(item.Type))
	if item.ID != "" {
		fmt.Fprintf(f, "ID: %s\n", item.ID)
	}
	fmt.Fprintf(f, "URL: %s\n", item.URL)
	fmt.Fprintf(f, "TITLE: %s\n", item.Title)
	fmt.Fprintln(f, sep)
	fmt.Fprintln(f)
	fmt.Fprintln(f, item.Content)
	fmt.Fprintln(f)
}

func itemTypeName(t types.ItemType) string {
	switch t {
	case types.ItemTypeJira:
		return "Jira Issue"
	case types.ItemTypeConfluence:
		return "Confluence Page"
	case types.ItemTypeWeb:
		return "Web Page"
	default:
		return string(t)
	}
}
