package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/jefflunt/contextual/internal/config"
	"github.com/jefflunt/contextual/internal/fetcher"
	"github.com/jefflunt/contextual/internal/logger"
	"github.com/jefflunt/contextual/internal/prompt"
	"github.com/jefflunt/contextual/internal/spider"
	"github.com/jefflunt/contextual/internal/types"
	"github.com/jefflunt/contextual/internal/writer"
	"github.com/jefflunt/contextual/pkg/version"
)

func main() {
	// Route stdlib log output to stderr; used only for fatal pre-logger errors.
	log.SetOutput(os.Stderr)
	log.SetFlags(0)

	args := os.Args[1:]

	// Detect 'confluence' subcommand.
	if len(args) > 0 && args[0] == "confluence" {
		handleConfluenceSubcommand(args[1:])
		os.Exit(0)
	}

	// Detect 'version' subcommand.
	if len(args) > 0 && args[0] == "version" {
		fmt.Println(version.Version)
		os.Exit(0)
	}

	// Detect 'help' subcommand.
	if len(args) > 0 && args[0] == "help" {
		printHelp()
		os.Exit(0)
	}

	// Parse flags.
	fs := flag.NewFlagSet("contextual", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	verbose := fs.Bool("verbose", false, "Print fetch details to stderr")
	fs.BoolVar(verbose, "v", false, "Print fetch details to stderr (shorthand)")
	progress := fs.Bool("progress", false, "Print a progress indicator to stderr")
	fs.BoolVar(progress, "p", false, "Print a progress indicator to stderr (shorthand)")

	if err := fs.Parse(args); err != nil {
		os.Exit(1)
	}
	itemArgs := fs.Args()

	if len(itemArgs) == 0 {
		fmt.Fprintln(os.Stderr, "Usage: contextual [--verbose|-v] [--progress|-p] <item> [<item> ...]")
		os.Exit(1)
	}

	// Determine logger mode.
	logMode := logger.ModeSilent
	switch {
	case *verbose:
		logMode = logger.ModeVerbose
	case *progress:
		logMode = logger.ModeProgress
	}

	lg, err := logger.New(logMode)
	if err != nil {
		log.Printf("[ERROR] Could not initialise logger: %v", err)
		os.Exit(1)
	}
	defer lg.Close()

	cfg, err := config.Load()
	if err != nil {
		lg.Warn("Could not load config: %v — see contextual.config.example.yml for setup instructions", err)
		cfg = &config.Config{}
	}

	// Validate required config options.
	if cfg.MaxContextLength == 0 {
		if prompt.PromptYesNo("Max context length not set. Set to 10240? [y/N] ") {
			cfg.MaxContextLength = 10240
		} else {
			lg.Error("max_context_length is required in config.yml")
			os.Exit(1)
		}
	}
	if cfg.Spider.MaxHops == 0 {
		if prompt.PromptYesNo("Spider max hops not set. Set to 2? [y/N] ") {
			cfg.Spider.MaxHops = 2
		} else {
			lg.Error("spider.max_hops is required in config.yml")
			os.Exit(1)
		}
	}

	s := spider.New(cfg, lg)

	// Resolve the output directory BEFORE fetching, to check for overwrite early.
	outputDir, errDir := os.Getwd()
	if errDir != nil {
		lg.Error("Could not determine output directory: %v", errDir)
		os.Exit(1)
	}

	// Write context.md — confirm overwrite if it already exists.
	contextPath := filepath.Join(outputDir, "context.md")
	if !prompt.ConfirmOverwrite(contextPath) {
		fmt.Fprintln(os.Stderr, "Aborted.")
		os.Exit(1)
	}

	items, err := s.Run(itemArgs)
	if err != nil {
		lg.Error("%v", err)
		os.Exit(1)
	}

	f, err := os.Create(contextPath)
	if err != nil {
		lg.Error("Could not create context file: %v", err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprintln(f, "This file was generated by the `contextual` tool. It contains fetched content")
	fmt.Fprintln(f, "from one or more sources (Jira issues, Confluence pages, and/or web pages),")
	fmt.Fprintln(f, "assembled to provide context for an AI agent or developer.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "Each section below represents a single fetched item. Sections are separated by")
	fmt.Fprintln(f, "a line of '=' characters and begin with a short metadata header (TYPE, ID, URL,")
	fmt.Fprintln(f, "TITLE), followed by the item's full content in Markdown format.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "The FIRST item is the primary subject — it corresponds directly to the first")
	fmt.Fprintln(f, "argument passed on the command line. All subsequent items are supporting context")
	fmt.Fprintln(f, "discovered via links, references, or related content within the primary item.")
	fmt.Fprintln(f, "")
	fmt.Fprintf(f, "Total items: %d\n", len(items))
	fmt.Fprintln(f)

	var bytesWritten int
	for i, item := range items {
		// Calculate size of item: content + approximate metadata overhead
		itemSize := len(item.Content) + 300
		if cfg.MaxContextLength > 0 && bytesWritten+itemSize > cfg.MaxContextLength {
			lg.Info("Reached max context length (%d bytes); truncating remaining %d items", cfg.MaxContextLength, len(items)-i)
			break
		}
		writeItem(f, item)
		bytesWritten += itemSize
	}

	fmt.Println(contextPath)
}

func writeItem(f *os.File, item types.Item) {
	sep := strings.Repeat("=", 80)
	fmt.Fprintln(f, sep)
	fmt.Fprintf(f, "TYPE: %s\n", itemTypeName(item.Type))
	if item.ID != "" {
		fmt.Fprintf(f, "ID: %s\n", item.ID)
	}
	fmt.Fprintf(f, "URL: %s\n", item.URL)
	fmt.Fprintf(f, "TITLE: %s\n", item.Title)
	fmt.Fprintln(f, sep)
	fmt.Fprintln(f)
	fmt.Fprintln(f, item.Content)
	fmt.Fprintln(f)
}

func printHelp() {
	fmt.Println("contextual: fetch and assemble context for AI agents.")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  contextual [--verbose|-v] [--progress|-p] <item> [<item> ...]")
	fmt.Println("  contextual confluence ... (manage Confluence pages and comments)")
	fmt.Println("  contextual version")
	fmt.Println("  contextual help")
	fmt.Println()
	fmt.Println("For more information, see: https://github.com/jefflunt/contextual/")
}

func itemTypeName(t types.ItemType) string {
	switch t {
	case types.ItemTypeJira:
		return "Jira Issue"
	case types.ItemTypeConfluence:
		return "Confluence Page"
	case types.ItemTypeWeb:
		return "Web Page"
	default:
		return string(t)
	}
}

func handleConfluenceSubcommand(args []string) {
	if len(args) < 2 {
		printConfluenceHelp()
		os.Exit(1)
	}

	subCmd := args[0]
	target := args[1]

	cfg, err := config.Load()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading config: %v\n", err)
		os.Exit(1)
	}
	if cfg.Atlassian.Host == "" || cfg.Atlassian.APIUser == "" || cfg.Atlassian.APIToken == "" {
		fmt.Fprintln(os.Stderr, "Error: Atlassian credentials (host, api_user, api_token) must be configured in ~/.contextual/config.yml")
		os.Exit(1)
	}

	host := cfg.Atlassian.Host
	email := cfg.Atlassian.APIUser
	token := cfg.Atlassian.APIToken

	switch {
	case subCmd == "create" && target == "space":
		if len(args) < 3 {
			fmt.Fprintln(os.Stderr, "Usage: contextual confluence create space <space-key> --title <title> [--parent <parent-page-id>] --body-file <file>")
			os.Exit(1)
		}
		spaceKey := args[2]

		fs := flag.NewFlagSet("confluence create space", flag.ExitOnError)
		title := fs.String("title", "", "Page title")
		parent := fs.String("parent", "", "Parent page ID (optional)")
		bodyFile := fs.String("body-file", "", "Path to file containing HTML body")
		fs.Parse(args[3:])

		if *title == "" || *bodyFile == "" {
			fmt.Fprintln(os.Stderr, "Error: --title and --body-file are required")
			os.Exit(1)
		}

		bodyBytes, err := os.ReadFile(*bodyFile)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error reading body file: %v\n", err)
			os.Exit(1)
		}

		pageID, err := writer.CreatePage(host, email, token, spaceKey, *title, *parent, string(bodyBytes))
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error creating page: %v\n", err)
			os.Exit(1)
		}
		fmt.Println(pageID)

	case subCmd == "update" && target == "page":
		if len(args) < 3 {
			fmt.Fprintln(os.Stderr, "Usage: contextual confluence update page <page-id> --title <title> --body-file <file>")
			os.Exit(1)
		}
		pageID := args[2]

		fs := flag.NewFlagSet("confluence update page", flag.ExitOnError)
		title := fs.String("title", "", "Page title")
		bodyFile := fs.String("body-file", "", "Path to file containing HTML body")
		fs.Parse(args[3:])

		if *title == "" || *bodyFile == "" {
			fmt.Fprintln(os.Stderr, "Error: --title and --body-file are required")
			os.Exit(1)
		}

		bodyBytes, err := os.ReadFile(*bodyFile)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error reading body file: %v\n", err)
			os.Exit(1)
		}

		err = writer.UpdatePage(host, email, token, pageID, *title, string(bodyBytes))
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error updating page: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("Successfully updated page %s\n", pageID)

	case subCmd == "search" && target == "page":
		fs := flag.NewFlagSet("confluence search page", flag.ExitOnError)
		title := fs.String("title", "", "Page title to search")
		space := fs.String("space", "", "Space key (optional)")
		fs.Parse(args[2:])

		if *title == "" {
			fmt.Fprintln(os.Stderr, "Error: --title is required")
			os.Exit(1)
		}

		pageID, err := fetcher.SearchConfluencePage(host, email, token, *title, *space)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error searching page: %v\n", err)
			os.Exit(1)
		}
		fmt.Println(pageID)

	case subCmd == "get" && target == "comments":
		if len(args) < 3 {
			fmt.Fprintln(os.Stderr, "Usage: contextual confluence get comments <page-id>")
			os.Exit(1)
		}
		pageID := args[2]

		commentsJSON, err := fetcher.GetConfluenceComments(host, email, token, pageID)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error getting comments: %v\n", err)
			os.Exit(1)
		}
		fmt.Println(string(commentsJSON))

	case subCmd == "reply" && target == "comment":
		if len(args) < 3 {
			fmt.Fprintln(os.Stderr, "Usage: contextual confluence reply comment <comment-id> --page-id <page-id> --body <body>")
			os.Exit(1)
		}
		commentID := args[2]

		fs := flag.NewFlagSet("confluence reply comment", flag.ExitOnError)
		pageID := fs.String("page-id", "", "Page ID of the comment")
		body := fs.String("body", "", "Reply message content")
		fs.Parse(args[3:])

		if *pageID == "" || *body == "" {
			fmt.Fprintln(os.Stderr, "Error: --page-id and --body are required")
			os.Exit(1)
		}

		replyID, err := writer.ReplyToComment(host, email, token, *pageID, commentID, *body)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error replying to comment: %v\n", err)
			os.Exit(1)
		}
		fmt.Println(replyID)

	default:
		printConfluenceHelp()
		os.Exit(1)
	}
}

func printConfluenceHelp() {
	fmt.Println("Usage:")
	fmt.Println("  contextual confluence create space <space-key> --title <title> [--parent <parent-page-id>] --body-file <file>")
	fmt.Println("  contextual confluence update page <page-id> --title <title> --body-file <file>")
	fmt.Println("  contextual confluence search page --title <title> [--space <space-key>]")
	fmt.Println("  contextual confluence get comments <page-id>")
	fmt.Println("  contextual confluence reply comment <comment-id> --page-id <page-id> --body <body>")
}
